### ISSUE TITLE
Double Clic notice du tchat

### ISSUE THREAD

**Issue by SquallX** [Xety/Xeta#125]
Hey,

Petite erreur sur la notice, lorsqu'un utilisateur double clique sur la notice du tchat une fenêtre s'ouvre et lui proposant de l'éditer rapidement. Evidemment vu qu'il n'a pas les autorisations un message l'informe qu'il n'a pas l'autorisation de modifier la notice.

En temps normal donc, la fenêtre d'édition ne devrait pas apparaître pour un membre ;)

![capture d ecran 2015-05-04 a 12 09 48](https://cloud.githubusercontent.com/assets/818564/7451886/7bfacc60-f256-11e4-9ed1-22d711555976.png)

**Comment by Xety** [comment]
Hey,
Effectivement, j'ai oublié de faire une condition sur le code JS.
Merci pour le report !

**Comment by Xety** [comment]
Je ferme, une PR est ouverte. Ref : #129
