### ISSUE TITLE
Error messages login/register

### ISSUE THREAD

**Issue by ghost** [Xety/Xeta#158]
Hi,

When connecting information without a password or username, the error display is not done on the correct form. Look preview.
![capture](https://cloud.githubusercontent.com/assets/4737018/7702925/e3d2b1d4-fe33-11e4-98e9-34d0683bb89e.PNG)

**Comment by Xety** [comment]
Thanks for the report. I will check that.

**Comment by Xety** [comment]
Closed as #158 is open now.
