### ISSUE TITLE
Add a category in admin panel to manage website

### ISSUE THREAD

**Issue by ghost** [Xety/Xeta#161]
Hi,

I don't know If I can propose a feature here, sorry in advance.
But I think it would be good If we can manage website on admin panel.

By adding a "Options" category, we can enable/disable chat on the forum, for example, enable/disable the website (as a maintenance system), an announce and others.

**Comment by JcPires** [comment]
I think it could be done with ACL permissions. I worked on them and i will add this feature soon

**Comment by DexX39** [comment]
Great ! And if I make changes to my side, I can update without crushing my changes?

**Comment by JcPires** [comment]
I think so, i will just modify:

* ACL: I will modify Acos / Aros / Acos_Aros 
* Groups: Add the TreeBahavior to be closest than Aro table "Need Xeta autorisation"and to facilitate   authorizations by inheritance 
* Admin's Groups views: Edit the pages add / edit / index to add acl management and inheritance

**Comment by DexX39** [comment]
Okay. In fact I've installed Xeta with composer to test. But if I want to put me on the trunk for future changes? Without removing what I'm doing, I can ?

**Comment by Xety** [comment]
@DexX39 That was already planned in my mind. But before this, i need to finish some others important stuffs.
Thanks for the suggestion.

**Comment by DexX39** [comment]
Happy to participate.

And compared to composer that's what I saw. I will add the new features in hand being careful.
I still have difficulties with cake sniff and test otherwise I have developed new features.

**Comment by Xety** [comment]
Closed as #188 is open now.
