### ISSUE TITLE
Like/Unlike blog articles doesn't work

### ISSUE THREAD

**Issue by Yinamon** [Xety/Xeta#174]
For some reason, I'm not able to like/unlike blog articles. I always get a red error message in the top right corner saying: Error to like/unlike the article. I have no idea where I should look for the error. Please help, thanks!

**Comment by Yinamon** [comment]
I get this error message in Chrome: https://dl.dropboxusercontent.com/spa/re2bt0q18afcfky/hciayx4i.png

**Comment by Xety** [comment]
Can you post the `Response` please ? 

Put the `debug` in `true` in your app.

In Chrome : `Inspect Element` => `Network` => `Select the failed request` => Tab `Response`

It will probably have a lot of code in the `Response`.

**Comment by Yinamon** [comment]
Here's the response: https://dl.dropboxusercontent.com/u/26226231/response.txt

I checked the preview and got this error: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous

Thanks for the fast reply btw!

**Comment by Yinamon** [comment]
Ahhh, I found the error! It's in the file Controller/BlogController at line 498:
I changed `'id' => $articleId` to `'BlogArticles.id' => $articleId`

Thanks for pointing out how to find the error! :D

**Comment by Xety** [comment]
Glad you found the error !
No problem, you're welcome ! Now you know how i debug to find an error with an AJAX call. :stuck_out_tongue:
