### ISSUE TITLE
Problème de route

### ISSUE THREAD

**Issue by neecride** [Xety/Xeta#176]
Salut,

Je test cakephp je débute et pour me faire la main je me base sur ton code.

après l’installation je tombe sur ça : 

`"Declaration of App\Routing\Route\SlugRoute::parse() should be compatible with Cake\Routing\Route\Route::parse($url, $method = '')"`

et bien-sur j'ai regarder dans les fichiers indiquer je n'y trouve rien comme solution.

**Comment by Xety** [comment]
Salut,
Ce projet n'a pas été mis à jour depuis plus d'un an, donc oui normal que tu rencontre quelque soucis à l'installation vue que le code du framework Cake a évolué depuis.
