### ISSUE TITLE
DB Structure is missing

### ISSUE THREAD

**Issue by dsoldo** [Xety/Xeta#227]
Hi,
after installation as it is described in the Documentation, Database structure is missing (tables). Is there any .sql dump file or something to import DB structure?

![image](https://user-images.githubusercontent.com/17589200/31616192-49c536ba-b28c-11e7-8601-5d19ff333224.png)

thx

**Comment by matscav** [comment]
Just run migrations.
Linux:
`bin/cake migrations migrate`
Windows:
`.\bin\cake migrations migrate`

**Comment by Xety** [comment]
As @MS10 said, you need to run the migrations and the seeds
