### ISSUE TITLE
Change default language?

### ISSUE THREAD

**Issue by koprals** [Xety/Xeta#229]
hi,
can you give me a tutorial to change the default language of this demo to en_US? cause the default language is fr_FR
thanks

**Comment by Xety** [comment]
Hey,
I haven't coded with Cake for a while, but if i remember well, the setting is located here : 
https://github.com/XetaIO/Xeta/blob/master/config/bootstrap.php#L115

And the option to change it is located here : 
https://github.com/XetaIO/Xeta/blob/master/config/app.default.php#L40

Note that the only locales accepted are located there : 
https://github.com/XetaIO/Xeta/blob/master/config/bootstrap.php#L120-L123
