### ISSUE TITLE
[ERRO] Unable to load config/app.php

### ISSUE THREAD

**Issue by luuckx2** [Xety/Xeta#53]
Hello! I'm Trying to Install How Does the tutorial.
composer create-project --dev xety/xeta <application_name>
and 
Import the file config/Schema/xeta.sql in your database.

However returns me the following error
Unable to load config / app.php . Create it by copying config / app.default.php to config / app.php
the file is correct in config / app.php..

**Comment by Xety** [comment]
Hello,
Like the error said, you need to rename the `config/app.default.php` to `config/app.php`.

**Comment by luuckx2** [comment]
Ta already done so. And the error continues

**Comment by Xety** [comment]
Ah yes, because the latest version have some bugs due to some updates in Cake3, i will release a new version soon, when i will finish my ACL.

Run this command instead of the command in the doc, to have the latest commit :
```
composer create-project --dev xety/xeta=dev-master <application-name>
```
