### ISSUE TITLE
How to change the language ?

### ISSUE THREAD

**Issue by luuckx2** [Xety/Xeta#54]
Hello , sorry to bother you. I'm having difficulties to change the language to Portuguese ( Brazil ) is there any tutorial?
Thank U

**Comment by Xety** [comment]
Hello,
Yes with the command that i given to you in the other issue, there is a internalionazation system. You will need to translate with [POEdit](http://poedit.net) those files : 
```
src/Locale/admin.pot
```
and
```
src/Locale/default.pot
```
into this directory:
```
src/Locale/pt_BR/
```

It's the same way as CakePHP2.

After, we need to add the new language there :
https://github.com/Xety/Xeta/blob/master/config/bootstrap.php#L113
```php
Configure::write('I18n.locales', [
    'en_US' => 'English',
    'fr_FR' => 'Français',
    'pt_BR' => 'Português (Brasil)'
]);
```

And i think it will be good. Let me know if you have some issues.

**Comment by luuckx2** [comment]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xeta.blog_articles_i18n' doesn't exist
This is return

**Comment by Xety** [comment]
You have installed the application with the master branch ?

**Comment by luuckx2** [comment]
Yes . When I install via composer always of the error that was not found app.php even copying the file and renaming . I made a clone and updated via composer . Only then could run

**Comment by Xety** [comment]
That's because you didn't installed the application with the cmd that i given to you in the other issue :
```
composer create-project --dev xety/xeta=dev-master <application-name>
```
